config/routes.rb
Rails.application.routes.draw do
resources :topics, only: [:index, :show]
  get 'topics/index'
  get 'topics/show'
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'aboutme', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'blog/:id', to: 'blogs#show', as: 'blog_show'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
     get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Kay's Portfolio", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Kay's Portfolio", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Kay's Portfolio", sticky: false) %>
<% end %>

app/views/shared/_application_footer.html.erb
     <div class="text-center container-fluid homefooter">
            <div class="copyright">
              <p> <%= copyright_generator %></p>
            </div>
          </div>

app/views/shared/_application_nav.html.erb
<div class="navbarresponsive">
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
  <div class="container">
    <%= link_to "Kayra Czerniewicz T.", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav ml-auto">
      <br>
       <%= nav_helper 'nav-link', 'span' %>
       <%= login_helper 'nav-link' %>
     </ul>
    </div>
  </div>
</nav>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="container-fluid blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Coding tutorials and more!</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
  <div class="container">
    <%= link_to "Kayra Czerniewicz", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav ml-auto">
       <%= nav_helper 'nav-link', 'span' %>
       <%= login_helper 'nav-link' %>
     </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Articles, Tutorials and more for Ruby, Rails, Javascript, HTML & CSS.</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/Kayracz" target="_blank"><i class="fab fa-github"></i></a></li>
      <li><a href="https://www.instagram.com/kayczt/" target="_blank"><i class="fab fa-instagram"></i></a></li>
      <li><a href="https://www.facebook.com/kayra.czerniewicz" target="_blank"><i class="fab fa-facebook"></i></a></li>
      <li><a href="www.linkedin.com/in/kayracz" target="_blank"><i class="fab fa-linkedin"></i></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
 <div class="<%= location %>">
  <div> <%= link_to "Home", root_path %> </div>
    <div> <%= link_to "About", aboutme_path %> </div>
    <div> <%= link_to "Contact", contact_path %> </div>
    <div> <%= link_to "Blog", blogs_path %> </div>
    <div> <%= link_to "Portfolio", portfolios_path %> </div>
    </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center headingportfolio">
      <div class="container">
        <h1 class="jumbotron-heading">My Portfolio</h1>
        <p class="lead text-muted">Recent Projects:</p>
        <p>
          <%= link_to 'Find Out More About Me', aboutme_path, class: 'btn btn-outline-primary' %></a>
          <!-- <#%= link_to 'My Blogs', blogs_path, class: 'btn btn-outline-primary' %></a> -->
        </p>
      </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Web-application development in Ruby-on-Rails. Front-end development with HTML5, CSS3, and Javascript. Responsive design using technologies like CSS3, Bootstrap, jQuery.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <%= login_helper 'text-white' %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Kayra Czerniewicz", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>